apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine-deployment
  labels:
    app: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
        - name: search-engine
          image: 'gcr.io/searchengine-381606/github.com/fabienducret/search-engine:$SHORT_SHA'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: search-engine
