apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine
  labels:
    app: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
