apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine-deployment
  labels:
    app: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
        - name: search-engine
          image: golang:1.20.2-bullseye
          ports:
            - containerPort: 8080
